2020-05-15 09:39:57,570 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:37]
2020-05-15 09:42:13,555 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:37]
2020-05-15 10:33:10,048 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:39]
2020-05-15 11:20:23,695 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:39]
2020-05-15 11:29:24,242 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:39]
2020-05-15 11:37:42,255 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:39]
2020-05-15 11:50:30,320 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:40]
2020-05-15 20:04:11,029 INFO: My Web starting up [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/__init__.py:40]
2020-05-15 20:04:22,814 ERROR: Exception on / [GET] [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/users/routes.py", line 9, in home
    return render_template('users/home.html')
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/home.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/layout.html", line 55, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/home.html", line 36, in block "content"
    Got something good- <a href="{{ url_for('send_me_an_email') }}">let me know</a> and thanks for your time.
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'send_me_an_email'. Did you mean 'users.send_me_an_email' instead?
2020-05-15 20:04:27,914 ERROR: Exception on / [GET] [in /home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/users/routes.py", line 9, in home
    return render_template('users/home.html')
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/home.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/layout.html", line 55, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/myweb/templates/users/home.html", line 36, in block "content"
    Got something good- <a href="{{ url_for('send_me_an_email') }}">let me know</a> and thanks for your time.
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/thistle/Desktop/FlaskApps/sites_in_production/MyWebsite/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'send_me_an_email'. Did you mean 'users.send_me_an_email' instead?
